### PR TITLE
Update core.py

### PR DESCRIPTION
**Pull request by ananth95**
Changed pyVim.connect to pyvim.connect.
Had issues with python3 and mac due to the uppercase letter

### CODE REVIEW

**Comment by dnaeon** [comment]
The package is indeed `pyVim` (with a capital `V`, not with lower-case `v`).

https://github.com/vmware/pyvmomi

Are you running your macOS with case-insensitive file system?

**Comment by ananth95** [comment]
Yeah just checked and it is APFS and case sensitive
```
   File System Personality:   APFS
   Type (Bundle):             apfs
   Name (User Visible):       APFS
   Owners:                    Enabled
```
Is there any other fix for this?

**Comment by dnaeon** [comment]
The output above seems to be for case-insensitive filesystem.

Here's what I see on my macOS, which uses a case-sensitive filesystem.

```
   Partition Type:            41504653-0000-11AA-AA11-00306543ECAC
   File System Personality:   Case-sensitive APFS
   Type (Bundle):             apfs
   Name (User Visible):       APFS (Case-sensitive)
   Owners:                    Enabled
```

Can you post the output from `diskutil info /`?

**Comment by ananth95** [comment]
Yeah Sorry I meant  to type case insensitive.
Is there any other fix for this?

**Comment by dnaeon** [comment]
You can try this one as well, but I wouldn't recommend this approach.

https://stackoverflow.com/questions/51732582/error-while-importing-pyvim-connect

I think your best approach would be to simply change that filesystem to case sensitive, just to avoid any further issues down the road.

**Comment by ananth95** [comment]
Yeah editing the site packages is not a great idea, so everyone with case insensitive file system has to edit their local copy?

**Comment by dnaeon** [comment]
Well, Python modules have a strict relationship with the actual filenames.

I dont use myself case insensitive filesystems, and you are very likely to
encounter other issues, if you continue using it.

Sorry, but I cannot accept this PR, as this would break legit clients on
Linux and macOS with case sensitive file systems.

**Comment by ananth95** [comment]
Yeah i am fine not accepting the PR .. but just wanna know if there is any other alternative for people like me :) 
Instead of editing the file .. can we do something with sys to provide a fix?

**Pull request closed without merging**
